### ISSUE TITLE
suggestion: skip inv open?

### ISSUE THREAD

**Issue by n0proxy** [tentose/Gw2QuickItem#2]
I'm aware that this is probably a step that can't be skipped for technical/api reasons, but I never let a question go unasked. So, is it possible to _not_ open the inventory screen after clicking an item's hud icon? Or to somehow open it invisibly instead?

**Comment by tentose** [comment]
Not possible I'm afraid. There is no special API to use an item. This module performs the exact same steps that the player would have to perform to use an item: open the inventory, find the item, double click on the item, close the inventory. Not opening the inventory would mean there's nothing to click on. 

Though I do have a feature planned to cache item locations within the inventory so that the window could stay open for a much shorter amount of time.
